# this script handles the instances created by deployer which are import
# everywhere when instances are needed so we wont need to create new ones.
erc20_instance = None
plasma_instance = None
erc721_instance = None
checksInstance = None

# function to set instances generated by deployer script.
def setInstances(_erc20_instance, _plasma_instance, _erc721_instance, _checksInstance):

    global erc20_instance
    global plasma_instance
    global erc721_instance
    global checksInstance

    erc20_instance = _erc20_instance
    plasma_instance = _plasma_instance
    erc721_instance = _erc721_instance
    checksInstance = _checksInstance
